services:
  discord-bot:
    image: dusehd1/discord-bot:latest
    container_name: discord-bot
    restart: unless-stopped
    ports:
      - "9482:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
